services:
  postgres:
    image: postgres:16-alpine
    container_name: devops_assessment_postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migrations/001_create_tables.sql:/docker-entrypoint-initdb.d/001_create_tables.sql:ro
      - ./db/migrations/002_indexes.sql:/docker-entrypoint-initdb.d/002_indexes.sql:ro
      - ./db/seeds/001_seed_data.sql:/docker-entrypoint-initdb.d/003_seed_data.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hotel_user -d hotel_db"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
